-- CONFIMAR PAGAMENTO DE PEDIDO
CREATE OR REPLACE FUNCTION CONFIMAR_PAGAMENTO_PEDIDO(
	ID_PDD INT,
    PRTCL_PAGAMENTO VARCHAR, 
	DT_PAGAMENTO DATE, 
	FRM_PAGAMENTO INT
) RETURNS VOID AS $$ 
DECLARE
    CURRENT_DATE TIMESTAMP;
    STTS_VENDA INT;
BEGIN
    STTS_VENDA = 2;
    CURRENT_DATE := 'NOW';
    UPDATE FROM PEDIDO 
    SET PROTOCOLO_PAGAMENTO = PRTCL_PAGAMENTO, 
        DATA_PAGAMENTO = DT_PAGAMENTO, 
        FORMA_PAGAMENTO = FRM_PAGAMENTO,
        DATA_ENVIO = CURRENT_DATE,
        STATUS_VENDA = STTS_VENDA
    WHERE ID_PEDIDO = ID_PDD;
END $$ LANGUAGE PLPGSQL;

-- CONFIRMAR ENTREGA DO PEDIDO

CREATE OR REPLACE FUNCTION PEDIDO_ENTREGUE(
    ID_PDD INT;
) RETURNS VOID AS $$
DECLARE
    CURRENT_DATE TIMESTAMP;
BEGIN
    CURRENT_DATE := 'NOW';
    UPDATE FROM PEDIDO
    SET DATA_ENTREGA = CURRENT_DATE
    WHERE ID_PEDIDO = ID_PDD;
END $$ LANGUAGE PLPGSQL;
