/*
* A SEGUIR, UMA SEQUENCIA DE TESTES PARA VERIFICAR POSSÍVEIS ERROS NA IMPLEMENTAÇAÕ DAS FUNCOES
*/

-- TESTES DA FUNCAO "REGISTRAR_LOJA(USUARIO VARCHAR, SENHA VARCHAR, NOME VARCHAR, DESCRICAO VARCHAR)"
SELECT REGISTRAR_LOJA(); -- ERROR:  function registrar_loja() does not exist
SELECT REGISTRAR_LOJA(''); -- ERROR:  function registrar_loja(unknown) does not exist
SELECT REGISTRAR_LOJA('', ''); -- ERROR:  function registrar_loja(unknown, unknown) does not exist
SELECT REGISTRAR_LOJA('', '', ''); -- ERROR:  function registrar_loja(unknown, unknown, unknown) does not exist
SELECT REGISTRAR_LOJA(NULL, NULL, NULL, NULL); -- ERROR:  O VALOR USUARIO NÃO PODE SER NULO, INFORME O USUARIO
SELECT REGISTRAR_LOJA('USUARIO', NULL, NULL, NULL); -- ERROR:  O VALOR SENHA NÃO PODE SER NULO, INFORME UMA SENHA
SELECT REGISTRAR_LOJA('USUARIO', 'SENHA123', NULL, NULL); -- ERROR:  O VALOR NOME NÃO PODE SER NULO, INFORME O NOME (ARGUMENTO NA POSICAO 2)
SELECT REGISTRAR_LOJA('USUARIO', 'SENHA123', 'NOME', NULL); -- ERROR:  O VALOR DESCRICAO NÃO PODE SER NULO, INFORME UMA DESCRICAO (ARGUMENTO NA POSICAO 3)
SELECT REGISTRAR_LOJA('USUARIO', 'SENHA123', 'NOME', 'DESCRICAO', 'VALOR A MAIS'); -- ERROR:  function registrar_loja(unknown, unknown, unknown, unknown, unknown) does not exist
SELECT REGISTRAR_LOJA('', '', '', ''); -- ERROR:  O VALOR USUÁRIO DEVE TER PELO MENOS 3 CARACTERES
SELECT REGISTRAR_LOJA('USUARIO', '', '', ''); -- ERROR:  A SENHA DEVE TER PELO MENOS 6 CARACTERES
SELECT REGISTRAR_LOJA('USUARIO', 'SENHA123', '', ''); -- ERROR:  O NOME DEVE TER PELO MENOS 3 CARACTERES
-- FUNÇÕES QUE REGISTRARAM OS DADOS
SELECT REGISTRAR_LOJA('USUARIO', 'SENHA123', 'NOME', ''); -- INFO:  LOJA REGISTRADA COM SUCESSO!
SELECT REGISTRAR_LOJA('USUARIO', 'SENHA', 'NOME', 'DESCRICAO'); -- INFO:  LOJA REGISTRADA COM SUCESSO!

